### ISSUE TITLE
Apply new names as decided in the pandaland decree of November 12

### ISSUE THREAD

**Issue by cafca** [p2panda/handbook#117]
It shall be known that from here on `Message` is called `Operation`
It shall be known that from here on `UserSchema` is called `ApplicationSchema`
It shall be known that from here on `Author` is called `PublicKey` unless it's an author in which case it's an author.

Let the brains burn!

**Comment by sandreae** [comment]
Message => Operation https://github.com/p2panda/p2panda/pull/156
