### ISSUE TITLE
Make `previousOperation` an array

### ISSUE THREAD

**Issue by sandreae** [p2panda/handbook#123]
## Summary

Replace `previousOperation` field in `Operation` with `previousOperations` which contains an array of the hash ids of all known graph tips (nodes in the graph with no subsequent operations).

## Description

Currently in an `Operation` we set a single `previousOperation` field containing a hash of the entry of the previous operation. This gives us a 1-1 causal relationship between all operations in a document, which we then sort topologically to arrive at a linear sequence.

Changing this to a situation where we have a `previousOperations` field which contains an array of operation id hashes would allow us to retain knowledge about _all tips_ which were known about when the operation is made. We currently lose this contextual information as soon as the graph moves on to a new state.

Making this change would bring us close to with how `automerge` and `tangle` record operation dependencies. Although we would still process the operations slightly differently.

This change would impact how we perform graph ordering. We would still topologically walk the graph, but instead of walking each branch until we reach a tip, we would walk until we reach a tip OR reach a node with >1 dependencies. We would still follow current LWW / highest-hash-wins branch reconciliation logic. The main difference would be that the sorting is slightly more fine grained and the ordering logic preserves causal relationships _between different branches_.

![Screenshot from 2021-12-12 10-13-05](https://user-images.githubusercontent.com/24291662/145715393-277e1708-6366-4daf-86d0-389258dee974.png)

In example (c) above, the topological sort of this graph would become:

**A <- B <- C <- D <- J <- E <- F <- G <-  K <- L <- M**

_(The interesting section is C <- D <- J <- E)_

## Pros

- more accurate sorting of the graph

## Cons

- not sure???

## Variations

A variation on this would be to leave `previousOperation` as it is but add a `heads` or `seenTips` field, which contains all un-merged graph tips. This way we retain the simple graph building a traversal possibilities of limiting previous dependencies to 1, but get the new context logic.

**Comment by cafca** [comment]
This is more accurate because operations, which were made with knowledge of other branches, are not anymore superseded by operations from other branches, when those other branches are favored due to hash sorting during topological ordering. Instead, we now allow operations from branches that "lose" in topological sorting to still be applied later (thus "win") when those operations were made under knowledge of the branch they would otherwise have been trumped by.

I like it!

**Comment by adzialocha** [comment]
Is this a vector clock?

**Comment by sandreae** [comment]
Not quite.... it's a different idea from our conversation around vector clocks. BUT I believe it would be possible to derive vector clocks from seq_nums and previousOperations if we need them (need to check this).

**Comment by sandreae** [comment]
UPDATE: added a variation on this idea.
