### ISSUE TITLE
Validation and data flows [TRACKING]

### ISSUE THREAD

**Issue by sandreae** [p2panda/handbook#126]
We need to specify where we expect validation to happen in our data pipelines, and what exactly this validation entails.

This is a tracking issue making sure we tackled all parts of validation, which can be roughly separated as:

1. Encoding ("shape of data")
    - [x] #26 
    - [x] #27 
2. API: Writing validation ("how to get data into a node") `publish` & `nextArgs`
    - [x] #195 
    - [x] #139
    - [x] #172
3. Persistence ("what do we need to store for what")
    - *TBC if this needs further specification*
4. Materialization ("process of bringing data into queryable shape")
    - [x] #120 
    - [x] #194
    - [x] #132
5. API: Reading ("how to get data from a node")
    - *TBC if this needs further specification*

**Comment by sandreae** [comment]
Yeh, I suppose, although my point here is that we need to take an overview of our validation strategy to make decisions about the individual items. We don't need three issues for this though ;-p

**Comment by sandreae** [comment]
Been working on an overview diagram here: https://whimsical.com/validation-flow-chart-C5iPuw34i5c3s7oyPgXrby

**Comment by sandreae** [comment]
Some possibly interesting takeaways:

- when receiving an entry + operation from a client for publishing, could we already run some validation of the previous_operations field of an operation before we accept it? Specifically:
    - the linked operations must exist in the designated document.
    - self-referencing not allowed (creates a cycle) not allowed.
    - no linking to operations "older" than ones already existing in this authors document log.
   
This would all require more knowledge about documents than we currently have at this "phase" of our implementation, maybe it's worth exploring though? Quite nice to reject operations which are clearly invalid from ever getting published.

**Comment by sandreae** [comment]
Some comments after workig on the spec the last week:

> self-referencing not allowed (creates a cycle) not allowed
Realised this is actually impossible as an operation doesn't know it's id before hashing, and it can't know the id of future operations, so all good.

> no linking to operations "older" than ones already existing in this authors document log.

We don't specify this yet, I'll add it to the brewing pot of ideas.

**Comment by sandreae** [comment]
Nearly there, this should be the final(ish) piece: https://github.com/p2panda/handbook/pull/248

We don't talk about persistence still, we are working under the assumption that a layer of persistence is assumed to be needed when looking at the data type validation requirements.

**Comment by adzialocha** [comment]
Amazing! This is done now, isn't it 🤩✨

**Comment by sandreae** [comment]
Yes!!! Wahoo!!
