### ISSUE TITLE
Give option to omit `previous_operations`

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#131]
.. use backlinks when they are not given.

This is interesting for single-writer updates!

**Comment by adzialocha** [comment]
Another thought (not that I'm against omitting previous operations) but still worth mentioning: By assuming there is something like "backlinks" one creates a dependency to the Bamboo data type

**Comment by sandreae** [comment]
Bumping this, I think it's a really nice idea to omit `previous_operations` when they are the same as backlinks.

It possibly offers us a pathway into single-writer documents which would be very bamboo-friendly as well. If we offer the possibility to enforce _no_ previous operations are set for entire documents.
