### ISSUE TITLE
To Materialise or Not To Materialise

### ISSUE THREAD

**Issue by sandreae** [p2panda/handbook#132]
During a chat with @cafca this question arose:

Given a document where we are missing (non-integeral) operation dependencies, do we, or do we not Materialise it? 

**Yes:** we Materialise it, and respond with a view which is missing operations.
- benefits:
    - we can respond with some value, which may be very useful and current.
- negatives:
    - we are responding with something we know is incomplete, this may make operations published now, appear later in a different context.

**No:** we understand this document to be incomplete and don't respond with any value.
- benefits:
  - we can be sure (I think) that the context (update history) of a document we update will not change
  - this actually makes DocumentView IDs (the hash of the graph tip/s) useful again, as we can be sure the document didn't/wom't change (as if it was incomplete, we would know, and not Materialise it)
    -  on second thoughts, we could Materialise it, as long as we don't allow publishing any new operations
- negatives:
  - if all a documents entries are not replicated (even non-integeral branches) then the whole document will be considered invalid and not materialised. This could result in documents just "disappearing" and/or being innaccesable for long periods.

I had assumed (not sure if we talked about it) that we were working under the assumption that we would Materialise everything where possible, even if some bits are missing (there could be an "outdated" flag somewhere. But both models are actually interesting, so let's discuss it.

**Comment by cafca** [comment]
I remember that we considered the strategy of materialising *as far as we can*, i.e. up to the last point where we have all operations. This results in the policy "if you want to publish an update you better make sure your dependencies are available" which sounds like a desirable dynamic. We can still materialise *something*, even if operations are missing at the end. If those missing dependencies stay missing the document may continue to evolve (i.e. be updated) from that "last known point".
