### ISSUE TITLE
Introduce strict single-writer schema

### ISSUE THREAD

**Issue by sandreae** [p2panda/handbook#134]
Been wondering a little more about sparse replication and how this works with our powerful multi-writer documents. I'm sure there are some really smart ways to make these two concepts play nicely together (firmly in the "things for the future" bag), but all that thinking lead me to this different, but complimentary, idea.

[caveat: maybe this idea is similar to the self-referencing-relation idea for ordering document logs?]
[another caveat: I'm just recording this idea so it doesn't fall out of my head and get lost, it may not be A Good Idea ;-p]

### Reasoning
- now that we have cool documents each in their own log then:
  - authors are more likely to have many short logs
  - document data is spread out across logs authored by different keypairs
  - sparse replication and materialisation of a document is.... funky....
  - and maybe not that beneficial for relatively short logs
- in some situations you might prefer to have one loooong log holding many instances of the same data, eg:
  - embedded devices streaming measurements
  - logging data
  - chat messages
  - festival news feeds ;-p
- in these cases multi-writer is less important, whereas ordering and taking advantage of efficient replication might be a priority

### Suggestion
- a new system schema which enforces the following properties:
  - strict single-writer logs
  - `previous_operations` is always committed, and the entries `backlink` is used instead
  - every `UPDATE` operation contains all fields defined buy the schema
    - resolution logic interprets each UPDATE as new data instance
    - (could instead stipulate the log can only contain `CREATE` operations?) 
    - i suppose this would materialise into a list?
 
 ### Bonus 
- If you want mutable fields in your feed, just have each operation contain a `relation` to a document :sparkle: 
- would be very compatible with SSB feeds, nice for cross compatibility?

**Comment by adzialocha** [comment]
Maybe I'm misunderstanding the point of this draft here but let me try another angle to the problem:

What is "sparse replication"? Its a way to only replicate parts of a log since you don't need all of them while preserving the cryptographic integrity.

The need of sparse replication comes in when you have one very long log (for example in SSB). When we organize documents by log we indeed have many small logs which makes "sparse replication" less necessary since our replication is already "sparse".

Surely it puts more work on the identifying log mechanism itself but in terms of "sparse replication" I wonder if we solve something with this draft? It feels a little bit like re-introducing the problem we don't have anymore, so we can solve it again :smile_cat:

**Comment by adzialocha** [comment]
Example: "embedded devices streaming measurements"

How does "sparse replication" look like when organizing **log per schema**:

```
# Loads of CREATE operations within one log, lets say its actually full of them, like 100.000 operations
Log 1: [1] <- [2] <- [3] <- [4] <- [5] <- [6] <- [7] <- [8] <- [9]

# .. but we're only interested in the last 3 entries! Then skiplinks help us!
# .. We only need to replicate the ones with a *
# .. and we get two features: a) We didn't download the whole log b) We still know the log integrity is intact
Log 1: [1*] <- [2] <- [3] <- [4*] <- [5] <- [6] <- [7*] <- [8*] <- [9*]
```

How does "sparse replication" look like when organizing **log per document**:


```
# Loads of CREATE operations within multiple logs, lets say its actually full of them, like 100.000 operations
Log 1: [1]
Log 2: [1]
Log 3: [1]
Log 4: [1]
Log 5: [1]
Log 6: [1]
Log 7: [1]
Log 8: [1]
Log 9: [1]

# .. but we're only interested in the last 3 entries! Just download them :-) 
Log 7: [1]
Log 8: [1]
Log 9: [1]
```

**Comment by adzialocha** [comment]
Not sure about naming it a "system schema" as well, since how we organize logs is not a "system schema" (like KeyGroup or SecretGroup) but a protocol-level definition.

**Comment by sandreae** [comment]
Huhuu! You are absolutely right, really great framing of the conversation :-)

I got stuck in the "how can we make the most of sparse replication" and forgot the "wow, isn't cool one author can have many logs" :rofl: 

Thanks for humouring me, I'm gunna close this.

**Comment by adzialocha** [comment]
> how can we make the most of sparse replication

Hehe, yes! Didn't mean to close this thread though, maybe you were onto something, just needs a different angle?

**Comment by sandreae** [comment]
Hmmm, ok, yes maybe, a different angle... I'll reopen for a bit, but it's ok to close if it get's stale. 

We chatted this over a little on Monday too, and came to the same conclusion really.

**Comment by sandreae** [comment]
> Not sure about naming it a "system schema"

Yeh, I wasn't sure about this either. I suppose I went with it as I imagined that this restriction would actually be enforced at document level. During resolution, single-writer rules for accepting operations would be enforced.

**Comment by sandreae** [comment]
The compatibility with SSB might be the most interesting element of this idea.

**Comment by sandreae** [comment]
Thinking about this once again. There could be a use case for this where:

1) the document you created is long lived and updated relatively often. 
2) it is referenced in an unpinned relation from a different document.

In this case, you would want:

- the newest state of the updated document to be reflected in the materialised parent document
- to utilise lipmaa links and payload deletion to keep the long living document lean
