### ISSUE TITLE
Description of `Persona`, a way to group a set of authors who represent a shared identity

### ISSUE THREAD

**Issue by cafca** [p2panda/handbook#15]
- content published is identified by being associated with a key pair
- when multiple devices are used to publish content a solution has been to place a copy of the key pair on each device which introduces all kinds of problems in key pair management
- instead we create a key pair per device and create another way of modeling identity:
  - when a user initially starts using p2panda using their device D1 they create a persona P, which is linked to their device's key pair - and publish it to the network 
  - when they want to use a second device D2 (which creates its own key pair) they publish a message using D2 that declares "i am the same as persona P"
  - when D1 receives this message it notifies the user that there was a "log-in attempt from a new device" and gives them the option to confirm or reject this
  - if the user confirms, D1 publishes a message that says "i accept D2's declaration"
  - now, the clients of other users can lookup the persona associated with the key pairs of D1 and D2, which is the same persona P
- TBD:
  - users can remove associated devices
  - users can create multiple personas 
  - a persona can be shared by multiple users
  - users can block devices from asserting identity with their device
  - users can assign metadata to persona-associations, e.g.
    - "this is P's mobile device"
    - "this device has limited rights"
    - "this device is not allowed to de-associate other key pairs from this persona"
    - "this device is a spokesperson posting on behalf of persona P"
    - "this is a bot posting on behalf of P"
    - "this is a bot controlled by persona P"
    - and others

# Schemas

## persona

- name: string

## persona-authorization-request

- persona: hash<persona>

## persona-authorization

- request: hash<persona-authorization-request>
- accepted: boolean

**Comment by adzialocha** [comment]
https://wolke.liebechaos.org/apps/files/?dir=/Verein/Projects/p2panda/Meetings&openfile=58986

**Comment by sandreae** [comment]
I understand much of the reason for needing Persona to have been replaced by KeyGroup. I feel there may still be a place for a Persona definition on top of KeyGroup, describing how KeyGroup is specifically used for shared identity across devices? A more abstract high-level description? (It's ok if not). This could come later too ;-p
