### ISSUE TITLE
The "why?" section

### ISSUE THREAD

**Issue by sandreae** [p2panda/handbook#154]
I think we're doing a really good job writing about the "how" of p2panda, in the handbook and all our nice code docs, but we are missing the "why" of p2panda :panda_face: let's find a nice place for this :+1:

**Comment by adzialocha** [comment]
You mean "why" we decided for certain specification details or "why" p2panda exists at all?

**Comment by sandreae** [comment]
Why it exists at all :-)

More a high level, public explanation.

**Comment by cafca** [comment]
To create an Internet that is so decentralised that it becomes resilient against infrastructure failure and global interventions.
To create an Internet that isn't _supplied_ by companies but _created_ by people and communities.
To create an Internet where data is controlled by the people it belongs to.
