### ISSUE TITLE
Do we need `OperationAction`s?

### ISSUE THREAD

**Issue by sandreae** [p2panda/handbook#177]
Slightly "out-of-nowhere" thought, but, I just wonder if we _need_ operation actions....?

Thinking of these scenarios:

- operation encoded on `Seq(1)` entry, no `previous_operations` = `CREATE`
- operation contained on > `Seq(1)` entry, with `OperationFields` = `UPDATE`
- operation contained on > `Seq(1)` entry, no `OperationFields` = `DELETE`
- operation contained on `Seq(1)` entry, with `previous_operations` and `OperationFields` = `UPDATE`
- operation contained on `Seq(1)` entry, with `previous_operations` but no `OperationFields` = `DELETE`

I think that covers all cases.

**Comment by cafca** [comment]
Yesterday it sounded like we all were in favor of keeping them. Can we close this?
