### ISSUE TITLE
Specify how to deal with deleted schemas

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#178]

**Comment by adzialocha** [comment]
> Two things to consider:
> 
> - Schemas are dependencies of documents, if schema authors are able to delete other people's documents by deleting a schema they probably have too much power.
> - Nodes are free to delete schemas anyway (permissionless principle) so a node should be able to just delete all schemas it doesn't have documents for or that it considers unimportant, just like it is able to decide not to materialise a schema to begin with.
> 
> The only reason I can see for allowing deletion of schemas is that they are signed data and therefore tied to a potentially identifiable real person who might want to distance themselves from creating that schema. 
>
> Is there another way around that?
> 
> I don't really have a good solution, seems like a hard problem actually! Maybe we just recommend not creating schemas with a key pair that is also used to publish information that can be tied to a natural person?

Nice writeup, I agree to all point!

I can imagine that some points can be tackled with a "please delete to safe my ass" operation in the future, similar to gdrp complaints etc. but that's future music.

Your mentioned risk I find true for everything else on the internet as well ala "whatever you do make sure it can be turned against you, therefore it's advisable to keep anonymous", I find suddenly mentioning it for schemas a little arbitrary. How about giving it a recommendation box under key pair in the spec?

**Comment by cafca** [comment]
Sounds good!
