### ISSUE TITLE
Rename `publishEntry` to `publish` and `nextEntryArgs` to `nextArgs`?

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#185]
Is `nextArgs` nice? What do we mean with "arguments"?

**Comment by cafca** [comment]
I found this definition which sounds like the name is adequate:

> A parameter is a variable in a function definition. It is a placeholder and hence does not have a concrete value.
> An argument is a value passed during function invocation.

https://www.educative.io/answers/parameter-vs-argument


I am in favor of `publish` and `nextArgs`!
