### ISSUE TITLE
Omit `schema_id` for DELETE operations?

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#187]
> To decide this we might need to maybe specify first how we understand "operations" and their regarding fields. I haven't made up my mind on this yet, here is the brain dump, there is a perspective on the operation specification which might help with understanding why or why not this makes sense (it's not only "optimization" and "shaving-off bytes", I think there is a risk for premature optimization):

### Actionable items

We could understand operations as "actionable" items, meaning that every operation holds an action which does _something_. In our case we currently have three actions defined: CREATE (action = `0`), UPDATE (action = `1`) and DELETE (action = `2`) but we can imagine many more actions in the future (for example RESTORE, PURGE or something special for blobs etc.).

### Features

In our current CRDT-thinking every operation is compatible with an operation graph, so operations can relate to each other and be brought in an order, this is one of the powerful features of our operations and realized with the `previous_operations` field. 

Another feature is that operations can contain application-data fields which need to follow a schema, this is also a powerful thing we provide. In other words: Application operations can contain data of any shape, and it can be validated against a schema! This is realized with the `fields` field, and probably only in combination with a `schema_id` field as we _need_ to know the schema to validate against.

### Specification of actions

I realize that most specification of _what_ an action as actually _doing_ is done through describing the materialization process. The "materializer" can work on operation items which have been brought in order and apply some "indexing" method on them, from first to last item. Describing the "indexing" method is probably how we would approach specifying what CREATE, UPDATE, DELETE, ... will do.

## Remove `schema_id` for DELETE?

Now we could argue that DELETE operations do _not_ make use of the `fields` feature, so they also don't need a `schema_id`! It's a thing which only comes in combination when using `fields`.

It helps to understand this from the perspective of a decoder which tries to make sense _what_ it is looking at. It does it in some sort of decision tree:

1. Check the `version`. Do I support it? Then go to the regarding branch of this version specification
2. Check the `action`. Do I support it? Then go the regarding branch of this action specification (for this version)
3. Do the next steps which are required by that "action", it can make use of different features. This is where the actual operation begins! :star:

For example:

CREATE has the action identifier `0` and makes use of the `schema_id` and `fields` feature.
UPDATE has the action identifier `1` and makes use of the `schema_id`, `previous_operations` and `fields` feature.
DELETE has the action identifier `2` and makes use of the `schema_id` and `previous_operations` feature.

.. this directly translates to the encoding format, for example for UPDATE:

`[1, 1, "schema_id_0020 ...", [0020 ...], { ... }]`

.. or DELETE:

`[1, 2, [0020 ...]`

## Implications

What does it mean for future things? We would need to be more strict on this distinction, for example, does a new "blob" operation _really_ need a `schema_id` to identify itself even when it doesn't use fields which are not validated against a schema (what would you validate it against anyhow, its binary "garbage")? Does it need new actions instead? Like BLOB_CREATE, BLOB_UPDATE, BLOB_DELETE (or I don't know what, this is just an example).

Similar to key packages for secret groups: Is it really a schema? Or is it actually a new sort of action? Like PUBLISH_KEY_PACKAGE? It doesnt make use of `fields` and therefore `schema_id` (its TLS encoded binary data) and `previous_operations` (its not using CRDTs) anyhow ..

What does that mean for "document per log id"? Maybe we need something more "abstract" to define a "document". Its not only something you can CREATE, UPDATE and DELETE on, otherwise a key package would not be a document?

**Comment by adzialocha** [comment]
This can also be discussed here: https://github.com/p2panda/handbook/issues/189

**Comment by adzialocha** [comment]
The counter approach would be that the schema id is more than just a tool for fields validation but actually has implications on how the action will behave, is a DELETE on an application document different than a DELETE on a schema document? Currently we say we deleted schemas only as "deprecated", which is already one "special case".

In this sense we could also see `(action, schema_id)` as the set which defines the rules of this operation and then we should keep it in DELETE for now and maybe "only" remove it as an optimization later?

**Comment by cafca** [comment]
Regarding schema id on deletes - It's hard to decide because I don't really have a good grasp of the implications for the future. However, delete operation payload size won't matter that much maybe? So I'd just leave it in in case it's helpful in the future. I wouldn't really mind if we remove it either though.

The action encoding I'm also on board with btw!

**Comment by cafca** [comment]
Our conversation around the role of schema ids yesterday sounded like we were in favor of making schema a queen 👑, then we would keep it even for delete operations and could close this issue?

**Comment by adzialocha** [comment]
> Our conversation around the role of schemas in operations yesterday sounded like we were in favor of making schema a queen 👑, then we would keep it even for delete operations and could close this issue?

Yes!!!!

**Comment by adzialocha** [comment]
👑
