### ISSUE TITLE
Document Index Log

### ISSUE THREAD

**Issue by cafca** [p2panda/handbook#190]
## Introduction

An append-only log ensures a temporal ordering on its entries such that entries with a higher sequence number must have been created later than those with lower sequence numbers. This helps in replication because nodes can exchange the highest sequence number they know about for each log + any missing sequence numbers from before that and know right away which data to exchange. 

As logs for an author in bamboo are not append-only (it would be possible to create log 1, then 5, then 2), we don't have it so easy. p2panda requires implementations to only use log numbers sequentially but there are no guarantees given on this. Some downsides:

- A buggy implementation might produce gaps in log numbers and this could lead to data not being replicated. 
- Identifying the next unused log id also requires checking for gaps
- It's not possible to reason about the temporal order of documents by comparing their log ids

## Proposal

A system schema `document_index` is used to track the assignment of logs to documents. A given log with the log id n (n > 0) is only considered valid if there is an entry with log id 0 and sequence number n and that entry's operation has a field `document` with the log's document id and a field `schema` with the log's schema. 

Logs are ignored / considered invalid when 

- there is no corresponding entry in the document index
- the corresponding document index contains a document id and/or schema that does not match the document id/schema that is encoded in the log itself

Advantages:
- As this index log is append-only we have made logs as a whole append-only as well
  - it is not possible anymore to inadvertently create gaps in log ids
  - the next available log id = the next sequence number of the document index log
  - we have certain information on the order of creation of logs that can be useful for applications
- In addition, by replicating the index log a node gains complete information necessary for replication by schema and replication by document id. 
  - this information does not depend on trusting the remote node to provide us accurate information, i.e. when we ask a malicious node "what logs of this pubkey are for schema x?" the node could just leave out some logs. if we have a document index log we have verified information about the set of logs for a given schema.

Disadvantages:
- starting a new log now requires publishing two entries instead of one
- information on the assignment of logs to documents/schemas is duplicated as it is contained in both the index log and the logs' first entries

### Schema: `document_index`
```yaml
name: document_index
description: Track the assignment of logs to documents.
fields:
  document: str
  schema: str
```

**Comment by cafca** [comment]
Would be curious to hear your opinion @sandreae @adzialocha. Especially the second listed advantage seems very strong to me. Of course the disadvantages weigh heavy as well..

**Comment by adzialocha** [comment]
I remember I had a conversation with @sandreae about your proposal as well during the last safari, and we realized we could enforce a strict `log_id` specification where you _have_ to pick the next free one, similar to `seq_num` (strictly monotonically growing). Surely that doesn't protect you from someone not following that rule, but thats an issue with many other things as well.

We can check if clients followed this rule by a) only replicating when log ids got sorted from lowest to highest (similar to `seq_num` again) b) deleting logs if we detect holes (similar to detecting a log fork, deleting operations when the relation inside of it didn't match the schema id or other things we can only do "after some time" / during materialization).

**Comment by sandreae** [comment]
I bumped into this again while browsing old issues. I have had it in mind a bit when thinking about efficient replication and and also document deletion. If document index logs are organised by schema, they would give us "highest log id" information for logs of each schema, which as you say, would be rather useful during replication. Also, for deletion, the index entry for a document would be helpful for handling some tricky edge cases around deleting logs by multiple authors who all contributed to the same (now deleted) document.

**Comment by sandreae** [comment]
The edge cases I'm refering to above are described here: https://github.com/p2panda/handbook/issues/272
