### ISSUE TITLE
Find a better name for `previous_operations`?

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#191]

**Comment by cafca** [comment]
I just read a little about graphs and DAGs and topological ordering to look for a technical term in that context. So, we could call it "edges" in the sense of "this operation is a new vertex in a document DAG. please also add edges starting at the new vertex and ending at the given operation ids".

**Comment by sandreae** [comment]
I'm gunna put my vote in firmly for `previous` 🔥

Reasons I really like it:
- it is simple and easy to understand "the thing that came before this thing"
- but still ambiguous in a good way, as it could refer to previous operations, document_view_id, state it doesn't matter, all are some how valid 🤣 (check the spec if you wanna know for sure).

**Comment by adzialocha** [comment]
I don't really have a strong opinion anymore since the field names are gone in the new operation format .. now it suddenly became a name for a field we want to refer to in code, tutorials and such. With this perspective:

I could say "Did you check the previous operations"? Then currently it would be fairly clear what I mean. It's the only place where we have _operations_ and a pointer to the previous ones.

"edges" feels a little too abstract, if I say "did you check the edges?" it might not be obious.
"previous" is a little better as we do not have any other concept named "previous", but still its fairly close to "backlink"?

I think I'm still fine with "previous operations". We could call them "predecessor_operations"? Then it gets even more clear that they happened "before". (similar to the new backlink name in Bamboo v2 https://github.com/AljoschaMeyer/bamboo/blob/master/bamboo2_draft.md).

**Comment by adzialocha** [comment]
More ideas:

"viewId"
"predecessors"

**Comment by adzialocha** [comment]
`previous`!
