### ISSUE TITLE
Client and Node API validation

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#195]
What data do we reject and accept when and how? This needs specification:

a) .. the "shape" of data (for example that binary data is represented as hex-encoded strings)
b) .. does the data "make sense" when put in context with what we know about it so far?

Some nice flow diagrams will be great here: https://whimsical.com/4X53TdGvPLFUtmuBFvriW5

**Comment by adzialocha** [comment]
> Should I add this to the whimsical?

Yes, please!

I'd put it in the SHOULD category, it's a good recommendation!

**Comment by cafca** [comment]
_When you check the check, mind the fork in the road.
If you fork the fork, your append-only log will be spoiled.
But if you keep your checks in check, then your forks will be fine.
Just make sure to check the check, and fork the fork with care._

**Comment by sandreae** [comment]
The general approach for API validation taken in the spec now is that what validation needs to take place should be infer-able (is that a word..?) from the relevant data type specification. There is also some clarification of which requirements need to be enforced on the different public APIs.

Closing in favour of more specific issue which is still open here: https://github.com/p2panda/handbook/issues/249
