### ISSUE TITLE
Change operation header format from map to array

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#200]
Before:

```yaml
version: 1
action: "update"
previous_operations: ["00206ef50a..."]
schema: "schema_field_definition_v1"
fields: { ... }
```

After:

```yaml
[1, 1, "schema_field_definition_v1", ["00206ef50a..."], { ... }]
```

`action` is an enum:

- `0`: create
- `1`: update
- `2`: delete

When `action` is `0`, the array omits the previous operations:

```yaml
[1, 0, "schema_field_definition_v1", { ... }]
```

---

**Aren't string enum values better?**

Sure, thats also an option to use `create`, `update`, `delete` instead of the number encoding. I'd be up for both options, what do you think?

**But now this is not readable anymore?**

I realized that our current binary encoding is _already_ not readable (you look at bytes!) and you need to throw it into wasser.liebechaos.org before if you want to understand whats going on. It's not really an issue related to _what_ format we pick. In any case, we could not only decode VV with the wasser tool but also add the fields again for human readibility.

**Can we optimize this even more?**

Yes, there is a ticket for that here: https://github.com/p2panda/handbook/issues/189 but I suggest this can be tackled later. I also have the feeling it can be done without any breaking changes.

**Does it make sense to use a schema-less encoder?**

This was a suggestion of @AljoschaMeyer which is interesting. It basically means we would define a strict encoding only for operations, similar to how Bamboo Entries are designed, so we would not use CBOR or VV for the operation format at all and gain some even slimmer payloads.

I still doubt its a good idea as we have dynamic array sizes in previous operations and also schema ids can look very different (either constant system schemas or application schemas with potentially longer document view ids ..). There might be a way to encode this smartly (use our knowledge of how schema ids are designed for example) but I'm afraid we will just reinvent a new encoding format which is already covered by CBOR or VV.

**Comment by AljoschaMeyer** [comment]
> version: 1

Just out of curiosity, do you start counting versions at 1 rather than 0? Also, is there a limit on how many different versions you can define, i.e., what is the type of the version field?

> Aren't string enum values better?

But, efficiency =P

Here's a (somewhat tongue-in-cheek) counter proposal: merge the version and the operation into a single number to save a byte: let `v` be the version, and `o` the operation number (0, 1, or 2), then encode the single number `3 * v + o`. That's probably the most efficient you will get, regardless of whether you go for schemaless encoding or not. Still, I'm just proving your point, am I not... =D

**Comment by adzialocha** [comment]
> > version: 1
> 
> Just out of curiosity, do you start counting versions at 1 rather than 0? Also, is there a limit on how many different versions you can define, i.e., what is the type of the version field?

Was wondering the same .. We could start with `0` here as well. What would you suggest? There is no limit I can think of, so probably it could be a `u64`?

> > Aren't string enum values better?
> 
> Still, I'm just proving your point, am I not... =D

Hahaha. :sheep:

**Comment by AljoschaMeyer** [comment]
While I am overthinking this: why do you need "create" in the first place? Just have an "update" with an empty array of "previous_operations". That feels a lot more natural to me than having a third action kind and changing the number of remaining fields based on the action.

> We could start with 0 here as well.

Please do =)

> There is no limit I can think of, so probably it could be a u64?

Agreed, up to encoding version and action together. If you eliminated the create action, you could use a u63, and use the last bit of encoding it as a u64 for encoding the action.

**Comment by cafca** [comment]
I think merging action and version is confusing, then I'd rather omit action altogether.

(although I still think we should leave open the option of creating "empty" `update`s that are just created in order to get a new view id or merge `previous_operations`.

**Comment by adzialocha** [comment]
> I think merging action and version is confusing, then I'd rather omit action altogether.

I agree!

> although I still think we should leave open the option of creating "empty" updates that are just created in order to get a new view id or merge previous_operations

Yes, thats an nice one (do we have a ticket for that!?).

**Comment by cafca** [comment]
> Yes, thats an nice one (do we have a ticket for that!?)

Our spec already allows for this:

> an update operation MAY contain any combination of fields from the operation's schema

**Comment by adzialocha** [comment]
> Our spec already allows for this:

I would not be able to read out of this that its also allowed to have empty `fields`, maybe we write this next to it in the specification?
