### ISSUE TITLE
Specify where we draw the border between clients and nodes

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#23]

**Comment by cafca** [comment]
Do you have some specific areas in mind where this distinction is not obvious?

**Comment by adzialocha** [comment]
> Do you have some specific areas in mind where this distinction is not obvious

Nodes

* Materialization
* Filtering
* Validation
* Aggregation
* Persistence
* Status

Clients

* En- / Decryption
* Data creation and signing
* Caching
