### ISSUE TITLE
Operation encoding validation

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#27]
#### CBOR

- Bytes encoded following the CBOR specification: https://datatracker.ietf.org/doc/html/rfc7049
  	- We do not make use of CBOR tags
	- SHOULD (Recommendation): Canonical CBOR encoding as per https://datatracker.ietf.org/doc/html/rfc7049#section-3.9
		- Note: If not followed, hashes will be different for the same content on different implementations (test vectors / examples will potentially not work across implementations)
		- Integers must be as small as possible
		- The expression of lengths in major types 2 through 5 must be as
      short as possible
	  - The keys in every map must be sorted lowest to highest
	  - Indefinite-length items must be made into definite-length items
	  - IEEE Floats are used, it is recommended to follow the    canonicalization rules by the CBOR specification
  - MUST We use CBOR in "strict" mode
	- Operations not following the rules of "strict" mode need to be rejected
	- This includes:
		- A map (major type 5) can not have duplicate keys
		- Incorrect formatting (value does not represent claimed type)
	- We do not have to worry about tags as we do not use them

#### Operation Format

- Map keys must match `^[A-Za-z]{1}[A-Za-z0-9_]{0,63}$` 
- Canonical format:
	- Similar to the canonical format of CBOR, p2panda recommends one for operations to assure same hashes across different implementations
	- All array values SHOULD be in sorted order (from lowest to highest) 
		- as long as the ordering does not hold semantic value, this is true for:
			- `previous_operations`
			- document view ids in pinned relations (also the ones inside of lists)
		- Arrays with semantic ordering (not sorted):
			- pinned relation lists
			- relation lists
- All operations MUST follow the Operation format encoding (`version`, `action`, `previous_operations`, `schema`, `fields`), specified here: https://p2panda.org/handbook/docs/writing-data/operations

**Comment by sandreae** [comment]
specified!
